// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijwqssenwfhreqxhliwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqd3Fzc2Vud2ZocmVxeGhsaXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA5NTM5MjksImV4cCI6MjEwNjUyOTkyOX0.ptJnKRJJKE7rQXXZ9Jo5Hg0WPKtKiymX_-1arOxZ8uY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});